#!/bin/bash

#SITE_PACKAGES="$HOME/Dev/python/site-packages"

if [ ! $SITE_PACKAGES ]
then
    SITE_PACKAGES=`python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()"`
fi

BASE=`basename $1`
DIR=`dirname $1`

cd $DIR
ln -sfnv `pwd`/$BASE $SITE_PACKAGES/$BASE
